Prevent overflow with fast render/update
tuzz/game-loop pull request #20
Opened 2023-10-21 19:29 UTC by Pyxrs

I noticed that with an extremely fast render or update function, the program would overflow after an insubstantial amount of time. This is simple fix.

2023-10-21 19:29 UTC, Pyxrs commented
Fixes the newly opened #19

2023-11-04 21:30 UTC, tversteeg requested changes

2023-11-04 21:30 UTC, tversteeg commented on src/base.rs
Wouldn't the following be a better solution? This can never overflow.

```rust
g.number_of_renders = g.number_of_renders.wrapping_add(1);`
g.number_of_updates = g.number_of_updates.wrapping_add(1);`
```

2023-11-04 22:23 UTC, Pyxrs reviewed
Yes, I agree. This would be ideal.

2023-11-04 22:28 UTC, Pyxrs commented
I decided to leave the u64s in place. Unless there is a substantial performance hit, keeping these higher will be inconsequential to memory and may mitigate unintended behavior by wrapping back to 0 less often.

2024-01-13 23:20 UTC, parasyte commented
Wrapping add is unnecessary with `u64`. See: https://github.com/tuzz/game-loop/issues/19#issuecomment-1890783420 but otherwise it looks good.

2024-01-16 14:10 UTC, tuzz commented
Thanks, resolved in https://github.com/tuzz/game-loop/commit/86ca2f5f84c35707bedcd024d659c1679cb007ba. Closes https://github.com/tuzz/game-loop/issues/19.

2024-01-16 14:10 UTC, closed without merging